export const AUTH = {
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_FAIL:"FETCH_USER_FAIL",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT"
  }