export const AUTH = {
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_FAIL:"FETCH_USER_FAIL",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT"
  }

export const ACTIVITIES = {
    FETCH_ACTIVITIES: "FETCH_ACTIVITIES",
    FETCH_ACTIVITIES_SUCCESS:"FETCH_ACTIVITIES_SUCCESS",
    FETCH_ACTIVITIES_FAILED: "FETCH_ACTIVITIES_FAILED"
}