export const AUTH = {
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",
    FETCH_USER_FAIL:"FETCH_USER_FAIL",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT"
  }

export const ACTIVITIES = {
    FETCH_ACTIVITIES: "FETCH_ACTIVITIES",
    FETCH_ACTIVITIES_SUCCESS:"FETCH_ACTIVITIES_SUCCESS",
    FETCH_ACTIVITIES_FAILED: "FETCH_ACTIVITIES_FAILED"
}

export const CONFIDENTIAL = {
    FETECH_CONFIDENTIAL: "FETCH_CONFIDENTIAL",
    FETECH_CONFIDENTIAL_SUCCES:"FETECH_CONFIDENTIAL_SUCCES",
    FETECH_CONFIDENTIAL_FAILED:"FETCH_ACTIVITIES_FAILED",
    CONFIDENTIAL: "CONFIDENTIAL",
    CONFIDENTIAL_SUCCES:"CONFIDENTIAL_SUCCES",
    CONFIDENTIAL_FAILED:"ACTIVITIES_FAILED",
    FETCH_COMMENTS: "FETCH_COMMENTS",
    FETCH_COMMENTS_SUCCES:"FETCH_COMMENTS_SUCCES",
    FETCH_COMMENTS_FAILED:"FETCH_COMMENTS_FAILED",
    POST_CONFIDENTIAL:"POST_CONFIDENTIAL"
}

