import Head from 'next/head'
import LayoutHome from "../component/layout/LayoutHome";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TLUS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutHome/>
    </div>
  )
}
